server:
  port: 8888
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotteon2/dailyon-config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: health, info, busrefresh, prometheus
